export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_COUNTRY = "GET_COUNTRY";
export const GET_COUNTRIESBYNAME = "GET_COUNTRYBYNAME";
export const ORDER_COUNTRIES = "ORDER_COUNTRIES";
export const ORDER_CONTINENT = "ORDER_CONTINENT";
export const ORDER_POPULATION = "ORDER_POPULATION";
